### ISSUE TITLE
The file opens in background

### ISSUE THREAD

**Issue by saumyajyoti** [Ape/open-with-cmd.yazi#2]
If I use bat as command the file opens in bat in background shell. Need to close Yazi to see the file. Is there a way to get it in a new shell over Yazi or close Yazi automatically?

**Comment by Ape** [comment]
Did you try this?

```
[[manager.prepend_keymap]]
on   = "o"
run  = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"
```

You might need to make your command block so that it doesn't exit immediately.

**Comment by saumyajyoti** [comment]
Thanks. The blocking one works as expected. What is the purpose of  non blocking one as documented in the readme? I see nothing if I run w/o block.

**Comment by Ape** [comment]
> Thanks. The blocking one works as expected. What is the purpose of  non blocking one as documented in the readme? I see nothing if I run w/o block. 

It's better if you launch a GUI application.
