### ISSUE TITLE
Deprecated API about args

### ISSUE THREAD

**Issue by c02y** [Ape/open-with-cmd.yazi#3]
When I use binding of open-with-cmd.yazi:

```
[[manager.prepend_keymap]]
on   = "o"
run  = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"

[[manager.prepend_keymap]]
on   = "O"
run  = "plugin open-with-cmd"
desc = "Open with command"
```

It popups an error window saying `Deprecated API`
![image](https://github.com/user-attachments/assets/ccc1de7e-1628-4d5f-9300-267b07609075)

Solution:
https://github.com/Ape/open-with-cmd.yazi/blob/8d7abc8a347bfa065b6d339d26480f6fdcfac37e/init.lua#L2-L3
change it to:
```lua
		entry = function(_, job)
			local block = job.args[1] and job.args[1] == "block"
```

FYI:
- yazi v0.4
- https://github.com/sxyazi/yazi/pull/1966

**Comment by victor4pinheiro** [comment]
I believe it's abandoned for a while. It's better for you to fork and send it to yazi plugin.
